# Comments
version: '1.0'

services:
  message-api:
    hostname: message-api
    image: maven:latest
    container_name: message-api
    working_dir: /usr/src/message
    depends_on:
      - message-db
    ports:
      - 8080:8080
    volumes:
      - ./:/usr/src/message
    command: "mvn clean spring-boot:run"

  message-db:
    hostname: message-db
    image: mariadb:latest
    restart: always
    ports:
      - 3306:3306
    volumes:
      - mariadb_data:/var/lib/mysql
    environment:
      MYSQL_USER: message
      MYSQL_PASSWORD: message
      MYSQL_DATABASE: message-db
      MYSQL_ROOT_PASSWORD: root

  adminer:
    image: adminer:latest
    container_name: adminer
    ports:
      - 8083:8080


volumes:
  mariadb_data: